export const users = [
    {
        id: '1',
        nama: 'Monkey D Luffy',
        title: 'Frontend Developer',
        department: 'Engineering',
        email: 'Luffy2@example.com',
        gambar: 'https://rricoid-assets.obs.ap-southeast-4.myhuaweicloud.com/berita/Wamena/f/1761906366035-IMG_20251031_192254/411fc7nfc705rhr.jpeg',
        portofolio: [
            { code: "FE001", nama: "UI Dashboard", image: "https://cdnb.artstation.com/p/assets/images/images/035/131/029/large/badger922-he-010a.jpg?1614177715" },
            { code: "FE002", nama: "Landing Page", image: "https://media.suara.com/pictures/970x544/2022/04/23/16530-negeri-wano-one-piece.jpg" },
            { code: "FE003", nama: "Portfolio Site", image: "https://froyonion.sgp1.cdn.digitaloceanspaces.com/images/blogdetail/38a4bad8e84b70d10e4242f5755ca7fdfe2b3db9.jpg" },
        ]
    },
    {
        id: '2',
        nama: 'Nami',
        title: 'Backend Developer',
        department: 'Engineering',
        email: 'namisan@example.com',
        gambar: 'https://static0.srcdn.com/wordpress/wp-content/uploads/2024/02/nami-from-one-piece.jpg?w=1600&h=900&fit=crop',
    },
    {
        id: '3',
        nama: 'Trafalgar D Water Law',
        title: 'UI/UX Designer',
        department: 'Design',
        email: 'trafalgarLaw@example.com',
        gambar: 'https://image.idntimes.com/post/20220916/1-17fb8060aa2d3a0a0afa9b023401535b.jpg',
    },
    {
        id: '4',
        nama: 'Roronoa Zoro',
        title: 'DevOps Engineer',
        department: 'Infrastructure',
        email: 'zoro@example.com',
        gambar: 'https://litfind.bookscape.com/wp-content/uploads/2025/02/Roronoa-Zoro_.jpg',
    },
    {
        id: '5',
        nama: 'Chopper',
        title: 'Mobile Developer',
        department: 'Engineering',
        email: 'chopperdr@example.com',
        gambar: 'https://tamashiiweb.com/images/item/item_0000015744_6LAiPf3P_400.jpg',
    },
    {
        id: '6',
        nama: 'Nico Robin',
        title: 'QA Engineer',
        department: 'Engineering',
        email: 'robin.nico@example.com',
        gambar: 'https://cdn.oneesports.id/cdn-data/sites/2/2022/04/One-Piece-Nico-Robin-Dress-Rosa-1-1024x539.png',
    },
    {
        id: '7',
        nama: 'Sanji',
        title: 'Data Scientist',
        department: 'Data',
        email: 'sanji@example.com',
        gambar: 'https://cdn.oneesports.id/cdn-data/sites/2/2024/01/One-Piece-Sanji-1.jpg',
    },
    {
        id: '8',
        nama: 'Brook',
        title: 'Product Manager',
        department: 'Product',
        email: 'brook@example.com',
        gambar: 'https://www.greenscene.co.id/wp-content/uploads/2025/05/brok1.png',
    },
    {
        id: '9',
        nama: 'Donquixote Doflamingo',
        title: 'Security Analyst',
        department: 'Infrastructure',
        email: 'doffie@example.com',
        gambar: 'https://cdn-jpr.jawapos.com/images/16/2025/05/05/Untitled-2-595603332.jpg',
    },
    {
        id: '10',
        nama: 'Kuzan',
        title: 'System Administrator',
        department: 'Infrastructure',
        email: 'aokiji@example.com',
        gambar: 'https://image.idntimes.com/post/20240407/aokiji-5912c0e5c62dc8bd055c353c53a3159f-59c4f5d3139818ee099c264bf7007a5a.jpg',
    },
    {
        id: '11',
        nama: 'Imu',
        title: 'UX Researcher',
        department: 'Design',
        email: 'imusan@example.com',
        gambar: 'https://c.inilah.com/reborn/2026/03/large_imu_one_piece_1_071d45e5c0.webp',
    },
    {
        id: '12',
        nama: 'Shanks',
        title: 'Fullstack Developer',
        department: 'Engineering',
        email: 'shanks@example.com',
        gambar: 'https://static.promediateknologi.id/crop/0x0:0x0/1200x600/webp/photo/p1/854/2025/02/17/Shanks-One-Piece-2299914278.jpg',
    },
];

export const user = users[0];